export const convertGapX = (value: string) => {
  switch (value) {
    case '1':
      return 'gap-x-[1px]';
    case '2':
      return 'gap-x-[2px]';
    case '3':
      return 'gap-x-[3px]';
    case '4':
      return 'gap-x-[4px]';
    case '5':
      return 'gap-x-[5px]';
    case '6':
      return 'gap-x-[6px]';
    case '7':
      return 'gap-x-[7px]';
    case '8':
      return 'gap-x-[8px]';
    case '9':
      return 'gap-x-[9px]';
    case '10':
      return 'gap-x-[10px]';
    case '11':
      return 'gap-x-[11px]';
    case '12':
      return 'gap-x-[12px]';
    case '13':
      return 'gap-x-[13px]';
    case '14':
      return 'gap-x-[14px]';
    case '15':
      return 'gap-x-[15px]';
    case '16':
      return 'gap-x-[16px]';
    case '17':
      return 'gap-x-[17px]';
    case '18':
      return 'gap-x-[18px]';
    case '19':
      return 'gap-x-[19px]';
    case '20':
      return 'gap-x-[20px]';
    case '21':
      return 'gap-x-[21px]';
    case '22':
      return 'gap-x-[22px]';
    case '23':
      return 'gap-x-[23px]';
    case '24':
      return 'gap-x-[24px]';
    case '25':
      return 'gap-x-[25px]';
    case '26':
      return 'gap-x-[26px]';
    case '27':
      return 'gap-x-[27px]';
    case '28':
      return 'gap-x-[28px]';
    case '29':
      return 'gap-x-[29px]';
    case '30':
      return 'gap-x-[30px]';
    case '31':
      return 'gap-x-[31px]';
    case '32':
      return 'gap-x-[32px]';
    case '33':
      return 'gap-x-[33px]';
    case '34':
      return 'gap-x-[34px]';
    case '35':
      return 'gap-x-[35px]';
    case '36':
      return 'gap-x-[36px]';
    case '37':
      return 'gap-x-[37px]';
    case '38':
      return 'gap-x-[38px]';
    case '39':
      return 'gap-x-[39px]';
    case '40':
      return 'gap-x-[40px]';
    case '41':
      return 'gap-x-[41px]';
    case '42':
      return 'gap-x-[42px]';
    case '43':
      return 'gap-x-[43px]';
    case '44':
      return 'gap-x-[44px]';
    case '45':
      return 'gap-x-[45px]';
    case '46':
      return 'gap-x-[46px]';
    case '47':
      return 'gap-x-[47px]';
    case '48':
      return 'gap-x-[48px]';
    case '49':
      return 'gap-x-[49px]';
    case '50':
      return 'gap-x-[50px]';
    default:
      return '';
  }
};
export const convertGapY = (value: string) => {
  switch (value) {
    case '1':
      return 'gap-y-[1px]';
    case '2':
      return 'gap-y-[2px]';
    case '3':
      return 'gap-y-[3px]';
    case '4':
      return 'gap-y-[4px]';
    case '5':
      return 'gap-y-[5px]';
    case '6':
      return 'gap-y-[6px]';
    case '7':
      return 'gap-y-[7px]';
    case '8':
      return 'gap-y-[8px]';
    case '9':
      return 'gap-y-[9px]';
    case '10':
      return 'gap-y-[10px]';
    case '11':
      return 'gap-y-[11px]';
    case '12':
      return 'gap-y-[12px]';
    case '13':
      return 'gap-y-[13px]';
    case '14':
      return 'gap-y-[14px]';
    case '15':
      return 'gap-y-[15px]';
    case '16':
      return 'gap-y-[16px]';
    case '17':
      return 'gap-y-[17px]';
    case '18':
      return 'gap-y-[18px]';
    case '19':
      return 'gap-y-[19px]';
    case '20':
      return 'gap-y-[20px]';
    case '21':
      return 'gap-y-[21px]';
    case '22':
      return 'gap-y-[22px]';
    case '23':
      return 'gap-y-[23px]';
    case '24':
      return 'gap-y-[24px]';
    case '25':
      return 'gap-y-[25px]';
    case '26':
      return 'gap-y-[26px]';
    case '27':
      return 'gap-y-[27px]';
    case '28':
      return 'gap-y-[28px]';
    case '29':
      return 'gap-y-[29px]';
    case '30':
      return 'gap-y-[30px]';
    case '31':
      return 'gap-y-[31px]';
    case '32':
      return 'gap-y-[32px]';
    case '33':
      return 'gap-y-[33px]';
    case '34':
      return 'gap-y-[34px]';
    case '35':
      return 'gap-y-[35px]';
    case '36':
      return 'gap-y-[36px]';
    case '37':
      return 'gap-y-[37px]';
    case '38':
      return 'gap-y-[38px]';
    case '39':
      return 'gap-y-[39px]';
    case '40':
      return 'gap-y-[40px]';
    case '41':
      return 'gap-y-[41px]';
    case '42':
      return 'gap-y-[42px]';
    case '43':
      return 'gap-y-[43px]';
    case '44':
      return 'gap-y-[44px]';
    case '45':
      return 'gap-y-[45px]';
    case '46':
      return 'gap-y-[46px]';
    case '47':
      return 'gap-y-[47px]';
    case '48':
      return 'gap-y-[48px]';
    case '49':
      return 'gap-y-[49px]';
    case '50':
      return 'gap-y-[50px]';
    default:
      return '';
  }
};
export const convertGap = (type: string, value: string) => {
  const gapObject = {
    gapX: convertGapX(value),
    gapY: convertGapY(value),
  };
  return gapObject[type as keyof typeof gapObject] || '';
};
